services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - /data/db
  fleetmanagement-svc:
    image: demo/fleetmanagement-svc:latest
    build:
      context: .
      dockerfile: src/Services/FleetManagementService/Api/FleetManagementService.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      # DEBUG >>>
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=fleetmanagement
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages
      - VSTEST_HOST_DEBUG=1
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_Kestrel__Endpoints__Http__Url=http://+:5001
      # DEBUG <<<
    ports:
      - 5001:5001
    volumes:
      # DEBUG >>>
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - .:/src
      # DEBUG <<<
    depends_on:
      - postgres