services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - /data/db
  fleetmanagement-svc:
    image: demo/fleetmanagement-svc:latest
    build:
      context: .
      dockerfile: src/Services/FleetManagementService/API/FleetManagementService.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
    ports:
      - 5001:5001
    depends_on:
      - postgres
  checklist-svc:
    image: demo/checklist-svc:latest
    build:
      context: .
      dockerfile: src/Services/ChecklistService/API/ChecklistService.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:4001
    ports:
      - 4001:4001
    